# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :custom_lane do |args|
    # add actions here: https://docs.fastlane.tools/actions
    build_app(
          workspace: "MCOEM.xcworkspace",
          scheme: args[:schemeName],
          export_method:"ad-hoc",
          export_xcargs: "-allowProvisioningUpdates",
          output_directory: "./fastlane/ipadFile",
          output_name: "project.ipa",
          configuration: "Release")
          
  end
end
